# Generated by Django 3.0.3 on 2020-04-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='artCredit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
