# Generated by Django 3.0.5 on 2020-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='artCredit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='mediaLinks',
            field=models.TextField(null=True),
        ),
    ]
