# Generated by Django 3.0.3 on 2020-04-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0002_auto_20200406_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='reactAngry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='reactLove',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='reactSad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='reactTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='reactUp',
            field=models.IntegerField(default=0),
        ),
    ]
