# Generated by Django 3.0.3 on 2020-04-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0002_auto_20200413_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='approvalState',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('rejected', 'rejected'), ('undecided', 'undecided')], default='undecided', max_length=9),
        ),
        migrations.AlterField(
            model_name='story',
            name='artCredit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='comfortablePublish',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no'), ('X', 'prefer not to share')], max_length=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='currentLocation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='knowPositive',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no'), ('X', 'prefer not to share')], max_length=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='major',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='story',
            name='reactAngry',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='reactLove',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='reactSad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='reactTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='reactUp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='responseAffected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='responseCommunity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='responseDoneDifferently',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='responseElse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryAcademic',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryFinancial',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryGovernment',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryHousing',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryMental',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='worryPhysical',
            field=models.CharField(blank=True, choices=[('NW', 'not worried'), ('SW', 'somewhat worried'), ('VW', 'very worried'), ('NA', 'prefer not to share')], max_length=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='year',
            field=models.CharField(blank=True, choices=[('HS', 'high school'), ('FR', 'freshman'), ('SO', 'sophomore'), ('JR', 'junior'), ('SR', 'senior+'), ('GR', 'graduate')], max_length=2),
        ),
    ]
