# Generated by Django 3.0.3 on 2020-04-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0003_auto_20200411_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='approvalState',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('undecided', 'undecided')], default='undecided', max_length=9),
        ),
    ]
