# Generated by Django 3.0.3 on 2020-04-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0003_auto_20200411_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='hometown',
            new_name='city',
        ),
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
