# Generated by Django 3.0.3 on 2020-04-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0004_auto_20200411_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
