# Generated by Django 3.0.3 on 2020-04-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_stories', '0005_story_country'),
        ('student_stories', '0004_story_approvalstate'),
    ]

    operations = [
    ]
